name: Continuous Integration - Backend

on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code
      - '.github/workflows/backend_ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t your-image-name:latest .
    
    - name: Check Docker Image Health
      run: |
        docker run --name temp-container your-image-name:latest
        docker inspect --format='{{.State.Health.Status}}' temp-container
        docker rm -f temp-container

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run Tests
      run: |
        # Add commands to run your tests inside the Docker container.
        # Example: docker run your-image-name:latest npm test