name: Continuous Deployment Workflow - Backend
on:
  push:
    branches:
      - main # Run the workflow only on push to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code within express directory
      - '.github/workflows/backend_cd.yml'

jobs:
  test:
    defaults:
        run:
            working-directory: ./backend

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        env:
          deploy_url: https://api.render.com/deploy/srv-cni0li21hbls73fet8i0?key=At7s5ZUvoNw
        run: |
          curl "$deploy_url"