name: Continuous Integration - Backend

on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code
      - '.github/workflows/backend_ci.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t backend:latest .
    
    - name: Run Docker image
      run: docker run -d --name frontend -p 4000:4000 backend:latest

    - name: Check running docker container
      run: docker ps

    - name: Wait for 20 seconds
      run: sleep 20

    - name: Test health of docker container
      run: curl -f http://localhost:4000/products/health || exit 1

  test-image:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    needs: build-image

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # - name: Set up system using docker-compose
    #   run: |
    #     docker-compose up -d --build
    
    - name: Run Tests
      run: |
        # Add commands to run your tests inside the Docker container.
        # Example: docker run your-image-name:latest npm test

  code-quality:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Lint Codebase
      run: npm run lint
