name: Continuous Deployment Workflow - Frontend
on:
  push:
    branches:
      - main # Run the workflow only on push to the main branch
    paths:
      - 'frontend/**' # Workflow triggered on changes to code within express directory
      - '.github/workflows/frontend_cd.yml'

jobs:
  test:
    defaults:
        run:
            working-directory: ./frontend

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: https://api.render.com/deploy/srv-cni53uf79t8c73bpp410?key=vxC30bBy7VY
        run: |
          curl "$deploy_url"